#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


REQUIRED_CITATION_FIELDS = ["title", "authors", "publisher", "publication_year"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit a markdown bundle generated by convert_pdf.py."
    )
    parser.add_argument("bundle_dir", type=Path)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero on warnings as well as failures.",
    )
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def has_boundary_slice(bundle_dir: Path, item: dict[str, Any], pdf_page: int, field: str) -> bool:
    spatial_output = item.get("spatial_output_path")
    if not spatial_output:
        return False
    spatial_path = bundle_dir / spatial_output
    if not spatial_path.exists():
        return False
    payload = load_json(spatial_path)
    for page in payload.get("pages", []):
        if page.get("pdf_page") == pdf_page and page.get(field) is not None:
            return True
    return False


def is_intentional_boundary_overlap(bundle_dir: Path, left: dict[str, Any], right: dict[str, Any]) -> bool:
    left_end = left.get("pdf_page_end")
    right_start = right.get("pdf_page_start")
    if not left_end or not right_start or left_end != right_start:
        return False
    return has_boundary_slice(bundle_dir, left, left_end, "slice_max_y") and has_boundary_slice(
        bundle_dir, right, right_start, "slice_min_y"
    )


def classify_leaf_range_overlap(left: dict[str, Any], right: dict[str, Any]) -> str | None:
    left_start = left.get("pdf_page_start")
    left_end = left.get("pdf_page_end")
    right_start = right.get("pdf_page_start")
    right_end = right.get("pdf_page_end")
    if not all([left_start, left_end, right_start, right_end]):
        return None
    if right_start > left_end:
        return None
    if left_start == right_start and left_end == right_end:
        return "identical"
    if right_start == left_end:
        return "boundary"
    if left_start <= right_start and right_end <= left_end:
        return "nested"
    return "overlap"


def main() -> int:
    args = parse_args()
    bundle_dir = args.bundle_dir.resolve()
    metadata_path = bundle_dir / "metadata.json"
    if not metadata_path.exists():
        raise SystemExit(f"Missing metadata.json in {bundle_dir}")

    metadata = load_json(metadata_path)
    issues: list[dict[str, Any]] = []
    file_manifest = metadata.get("file_manifest", [])
    citation = metadata.get("citation", {})

    for field in REQUIRED_CITATION_FIELDS:
        value = citation.get(field)
        if field == "authors":
            if not value:
                issues.append({"severity": "fail", "code": "missing_authors"})
            continue
        if value in (None, "", []):
            issues.append({"severity": "warn", "code": f"missing_{field}"})

    seen_paths: Counter[str] = Counter()
    for item in file_manifest:
        relative_path = item.get("output_path")
        if not relative_path:
            issues.append({"severity": "fail", "code": "manifest_missing_output_path", "item": item})
            continue
        seen_paths[relative_path] += 1
        path = bundle_dir / relative_path
        if not path.exists():
            issues.append(
                {"severity": "fail", "code": "missing_output_file", "output_path": relative_path}
            )
            continue
        text = path.read_text(encoding="utf-8")
        if "TODO" in text:
            issues.append({"severity": "fail", "code": "todo_marker_left_in_output", "output_path": relative_path})
        if "```text" in text:
            issues.append({"severity": "warn", "code": "layout_code_block_in_semantic_markdown", "output_path": relative_path})
        page_start = item.get("pdf_page_start")
        page_end = item.get("pdf_page_end")
        if page_start and page_end and page_end >= page_start and len(text.strip()) < 80:
            issues.append({"severity": "warn", "code": "suspiciously_short_output", "output_path": relative_path})
        spatial_output = item.get("spatial_output_path")
        if page_start and page_end:
            if not spatial_output:
                issues.append({"severity": "fail", "code": "missing_spatial_output_path", "output_path": relative_path})
            elif not (bundle_dir / spatial_output).exists():
                issues.append({"severity": "fail", "code": "missing_spatial_file", "output_path": relative_path, "spatial_output_path": spatial_output})
        flat_output = item.get("flat_output_path")
        if not item.get("child_ids"):
            if not flat_output:
                issues.append({"severity": "warn", "code": "missing_flat_leaf_export", "output_path": relative_path})
            elif not (bundle_dir / flat_output).exists():
                issues.append({"severity": "fail", "code": "missing_flat_leaf_file", "output_path": relative_path, "flat_output_path": flat_output})
            rag_output = item.get("rag_output_path")
            if page_start and page_end:
                if not rag_output:
                    issues.append({"severity": "warn", "code": "missing_rag_leaf_export", "output_path": relative_path})
                elif not (bundle_dir / rag_output).exists():
                    issues.append({"severity": "fail", "code": "missing_rag_leaf_file", "output_path": relative_path, "rag_output_path": rag_output})

    duplicates = [path for path, count in seen_paths.items() if count > 1]
    for duplicate in duplicates:
        issues.append({"severity": "fail", "code": "duplicate_output_path", "output_path": duplicate})

    leaf_ranges = []
    for item in file_manifest:
        kind = item.get("kind")
        if kind not in {"frontmatter", "section", "epilogue", "index", "auxiliary"}:
            continue
        start = item.get("pdf_page_start")
        end = item.get("pdf_page_end")
        if start and end:
            leaf_ranges.append((start, end, item.get("output_path"), item))

    leaf_ranges.sort()
    for previous, current in zip(leaf_ranges, leaf_ranges[1:]):
        overlap_kind = classify_leaf_range_overlap(previous[3], current[3])
        if overlap_kind == "boundary" and is_intentional_boundary_overlap(bundle_dir, previous[3], current[3]):
            continue
        if overlap_kind == "identical":
            issues.append(
                {
                    "severity": "fail",
                    "code": "invalid_leaf_range_overlap",
                    "kind": overlap_kind,
                    "left": previous[2],
                    "right": current[2],
                }
            )
            continue
        if overlap_kind in {"nested", "overlap", "boundary"}:
            issues.append(
                {
                    "severity": "fail" if overlap_kind == "nested" else "warn",
                    "code": "invalid_leaf_range_overlap" if overlap_kind == "nested" else "overlapping_leaf_ranges",
                    "kind": overlap_kind,
                    "left": previous[2],
                    "right": current[2],
                }
            )

    complex_pages = metadata.get("layout_profiles", {}).get("complex_pages", [])
    if complex_pages:
        ratio = len(complex_pages) / max(metadata["source"].get("page_count", 1), 1)
        if ratio > 0.35:
            issues.append({"severity": "warn", "code": "high_complex_layout_ratio", "ratio": ratio})

    severity_order = {"fail": 2, "warn": 1}
    highest = max((severity_order.get(issue["severity"], 0) for issue in issues), default=0)
    status = "pass"
    if highest == 2:
        status = "fail"
    elif highest == 1:
        status = "warn"

    report = {
        "bundle_dir": str(bundle_dir),
        "status": status,
        "issue_count": len(issues),
        "issues": issues,
        "file_count": len(file_manifest),
        "complex_page_count": len(complex_pages),
    }
    print(json.dumps(report, indent=2))

    if status == "fail":
        return 1
    if status == "warn" and args.strict:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
